[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Add the xp bar and text to the left UI underneath the chips x mult indicator

#  Adjust the size of existing elements
# This could be split into smaller patches to target specific lines/snippets but this works for now
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''contents.hand =
        {n=G.UIT.R, config={align = "cm", id = 'hand_text_area', colour = darken(G.C.BLACK, 0.1), r = 0.1, emboss = 0.05, padding = 0.03}, nodes={
            {n=G.UIT.C, config={align = "cm"}, nodes={
              {n=G.UIT.R, config={align = "cm", minh = 1.1}, nodes={
                {n=G.UIT.O, config={id = 'hand_name', func = 'hand_text_UI_set',object = DynaText({string = {{ref_table = G.GAME.current_round.current_hand, ref_value = "handname_text"}}, colours = {G.C.UI.TEXT_LIGHT}, shadow = true, float = true, scale = scale*1.4})}},
                {n=G.UIT.O, config={id = 'hand_chip_total', func = 'hand_chip_total_UI_set',object = DynaText({string = {{ref_table = G.GAME.current_round.current_hand, ref_value = "chip_total_text"}}, colours = {G.C.UI.TEXT_LIGHT}, shadow = true, float = true, scale = scale*1.4})}},
                {n=G.UIT.T, config={ref_table = G.GAME.current_round.current_hand, ref_value='hand_level', scale = scale, colour = G.C.UI.TEXT_LIGHT, id = 'hand_level', shadow = true}}
              }},
              {n=G.UIT.R, config={align = "cm", minh = 1, padding = 0.1}, nodes={
                {n=G.UIT.C, config={align = "cr", minw = 2, minh =1, r = 0.1,colour = G.C.UI_CHIPS, id = 'hand_chip_area', emboss = 0.05}, nodes={
                    {n=G.UIT.O, config={func = 'flame_handler',no_role = true, id = 'flame_chips', object = Moveable(0,0,0,0), w = 0, h = 0}},
                    {n=G.UIT.O, config={id = 'hand_chips', func = 'hand_chip_UI_set',object = DynaText({string = {{ref_table = G.GAME.current_round.current_hand, ref_value = "chip_text"}}, colours = {G.C.UI.TEXT_LIGHT}, font = G.LANGUAGES['en-us'].font, shadow = true, float = true, scale = scale*2.3})}},
                    {n=G.UIT.B, config={w=0.1,h=0.1}},
                }},
                {n=G.UIT.C, config={align = "cm"}, nodes={
                  {n=G.UIT.T, config={text = "X", lang = G.LANGUAGES['en-us'], scale = scale*2, colour = G.C.UI_MULT, shadow = true}},
                }},
                {n=G.UIT.C, config={align = "cl", minw = 2, minh=1, r = 0.1,colour = G.C.UI_MULT, id = 'hand_mult_area', emboss = 0.05}, nodes={
                  {n=G.UIT.O, config={func = 'flame_handler',no_role = true, id = 'flame_mult', object = Moveable(0,0,0,0), w = 0, h = 0}},
                  {n=G.UIT.B, config={w=0.1,h=0.1}},
                  {n=G.UIT.O, config={id = 'hand_mult', func = 'hand_mult_UI_set',object = DynaText({string = {{ref_table = G.GAME.current_round.current_hand, ref_value = "mult_text"}}, colours = {G.C.UI.TEXT_LIGHT}, font = G.LANGUAGES['en-us'].font, shadow = true, float = true, scale = scale*2.3})}},
                }}
              }}
            }}
          }}'''
position = "at"
payload = '''contents.hand =
  {n=G.UIT.R, config={align = "cm", id = 'hand_text_area', colour = darken(G.C.BLACK, 0.1), r = 0.1, emboss = 0.05, padding = 0.03}, nodes={
      {n=G.UIT.C, config={align = "cm"}, nodes={
        {n=G.UIT.R, config={align = "cm", minh = 0.7}, nodes={
          {n=G.UIT.O, config={id = 'hand_name', func = 'hand_text_UI_set',object = DynaText({string = {{ref_table = G.GAME.current_round.current_hand, ref_value = "handname_text"}}, colours = {G.C.UI.TEXT_LIGHT}, shadow = true, float = true, scale = scale*1.8})}},
          {n=G.UIT.O, config={id = 'hand_chip_total', func = 'hand_chip_total_UI_set',object = DynaText({string = {{ref_table = G.GAME.current_round.current_hand, ref_value = "chip_total_text"}}, colours = {G.C.UI.TEXT_LIGHT}, shadow = true, float = true, scale = scale*1.8})}},
          {n=G.UIT.T, config={ref_table = G.GAME.current_round.current_hand, ref_value='hand_level', scale = scale*0.7, colour = G.C.UI.TEXT_LIGHT, id = 'hand_level', shadow = true}}
        }},
        {n=G.UIT.R, config={align = "cm", minh = 0.5, padding = 0.1}, nodes={
          {n=G.UIT.C, config={align = "cr", minw = 2, minh =0.5, r = 0.1,colour = G.C.UI_CHIPS, id = 'hand_chip_area', emboss = 0.05}, nodes={
              {n=G.UIT.O, config={func = 'flame_handler',no_role = true, id = 'flame_chips', object = Moveable(0,0,0,0), w = 0, h = 0}},
              {n=G.UIT.O, config={id = 'hand_chips', func = 'hand_chip_UI_set',object = DynaText({string = {{ref_table = G.GAME.current_round.current_hand, ref_value = "chip_text"}}, colours = {G.C.UI.TEXT_LIGHT}, font = G.LANGUAGES['en-us'].font, shadow = true, float = true, scale = scale*1.3})}},
              {n=G.UIT.B, config={w=0.1,h=0.1}},
          }},
          {n=G.UIT.C, config={align = "cm"}, nodes={
            {n=G.UIT.T, config={text = "X", lang = G.LANGUAGES['en-us'], scale = scale*1, colour = G.C.UI_MULT, shadow = true}},
          }},
          {n=G.UIT.C, config={align = "cl", minw = 2, minh=0.5, r = 0.1,colour = G.C.UI_MULT, id = 'hand_mult_area', emboss = 0.05}, nodes={
            {n=G.UIT.O, config={func = 'flame_handler',no_role = true, id = 'flame_mult', object = Moveable(0,0,0,0), w = 0, h = 0}},
            {n=G.UIT.B, config={w=0.1,h=0.1}},
            {n=G.UIT.O, config={id = 'hand_mult', func = 'hand_mult_UI_set',object = DynaText({string = {{ref_table = G.GAME.current_round.current_hand, ref_value = "mult_text"}}, colours = {G.C.UI.TEXT_LIGHT}, font = G.LANGUAGES['en-us'].font, shadow = true, float = true, scale = scale*1.3})}},
          }}
        }}
      }}
  }}
'''
match_indent = true
# Add the xp bar underneath
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''contents.dollars_chips = {n=G.UIT.R, config={align = "cm",r=0.1, padding = 0,colour = G.C.DYN_UI.BOSS_MAIN, emboss = 0.05, id = 'row_dollars_chips'}, nodes={'''
position = "before"
payload = '''
contents.hand =
    {n=G.UIT.R, config={align='cm', colour = G.C.CLEAR}, nodes = {
        contents.hand,
        -- Add the xp bar to the left UI
        {n = G.UIT.R, config = {align = "cm", padding = 0.02}, nodes = {
            create_progress_bar({reverse_fill = false, bar_rotation = "Horizontal", w = 4.7, h = 0.25, ref_table = G.GAME, ref_value = 'ygg_current_xp', min = 0, max = 100})
        }},
        -- Add xp bar text to the left UI
        {n = G.UIT.R, config = {align = "tm", padding = setPadding}, nodes = {
            {n = G.UIT.O, config = {object = DynaText({scale = 0.3, string = {{ref_table = ygg_to_refer_level_bar, ref_value = "text"}}, maxw = 4.5, colours = { G.C.WHITE }, float = true, shadow = true, silent = true})}}
        }},
    }}
'''
match_indent = true

## Patches to stop resized texts reverting size when they are updated
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''e.config.object.scale = scale_number(G.GAME.current_round.current_hand.chips, 0.9, 1000)'''
position = "at"
payload = '''e.config.object.scale = scale_number(G.GAME.current_round.current_hand.chips, 0.4, 1000)'''
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''e.config.object.scale = scale_number(G.GAME.current_round.current_hand.mult, 0.9, 1000)'''
position = "at"
payload = '''e.config.object.scale = scale_number(G.GAME.current_round.current_hand.mult, 0.4, 1000)'''
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''if G.GAME.current_round.current_hand.handname:len() >= 13 then
      e.config.object.scale = 12*0.56/G.GAME.current_round.current_hand.handname:len()
    else
      e.config.object.scale = 2.4/math.sqrt(G.GAME.current_round.current_hand.handname:len()+5)
    end'''
position = "at"
payload = '''if G.GAME.current_round.current_hand.handname:len() >= 13 then
      e.config.object.scale = 8*0.56/G.GAME.current_round.current_hand.handname:len()
    else
      e.config.object.scale = 1.6/math.sqrt(G.GAME.current_round.current_hand.handname:len()+5)
    end'''
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''e.config.object.scale = scale_number(G.GAME.current_round.current_hand.chip_total, 0.95, 100000000)'''
position = "at"
payload = '''e.config.object.scale = scale_number(G.GAME.current_round.current_hand.chip_total, 0.75, 100000000)'''
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''
e.config.object:set_alignment({
        major = e.parent,
        type = 'bmi',
        offset = {x=0,y=0},
        xy_bond = 'Weak'
    })
'''
position = "at"
payload = '''
e.config.object:set_alignment({
        major = e.parent,
        type = 'bmi',
        offset = {x=0,y=0.1},
        xy_bond = 'Weak'
    })
'''
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''e.config.object = Sprite(0, 0, 2.5, 2.5, G.ASSET_ATLAS["ui_1"], {x = 2, y = 0})'''
position = "at"
payload = '''e.config.object = Sprite(0, 0, 2.5, 1.6, G.ASSET_ATLAS["ui_1"], {x = 2, y = 0})'''
match_indent = true